#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandleWebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test_device_db")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertonline_record(online_record instance);
    partial void Updateonline_record(online_record instance);
    partial void Deleteonline_record(online_record instance);
    partial void Inserthistory_record(history_record instance);
    partial void Updatehistory_record(history_record instance);
    partial void Deletehistory_record(history_record instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["test_device_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<online_record> online_records
		{
			get
			{
				return this.GetTable<online_record>();
			}
		}
		
		public System.Data.Linq.Table<history_record> history_records
		{
			get
			{
				return this.GetTable<history_record>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.online_record")]
	public partial class online_record : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _imei;
		
		private string _receivedTime;
		
		private string _longitude;
		
		private string _latitude;
		
		private string _speed;
		
		private string _mnc;
		
		private string _lac;
		
		private string _sos;
		
		private string _strong_box_open;
		
		private string _engine_on;
		
		private string _stopping;
		
		private string _gps_lost;
		
		private string _image_cam1;
		
		private string _image_cam2;
		
		private string _rfid;
		
		private string _obd;
		
		private string _version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OnreceivedTimeChanging(string value);
    partial void OnreceivedTimeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(string value);
    partial void OnlatitudeChanged();
    partial void OnspeedChanging(string value);
    partial void OnspeedChanged();
    partial void OnmncChanging(string value);
    partial void OnmncChanged();
    partial void OnlacChanging(string value);
    partial void OnlacChanged();
    partial void OnsosChanging(string value);
    partial void OnsosChanged();
    partial void Onstrong_box_openChanging(string value);
    partial void Onstrong_box_openChanged();
    partial void Onengine_onChanging(string value);
    partial void Onengine_onChanged();
    partial void OnstoppingChanging(string value);
    partial void OnstoppingChanged();
    partial void Ongps_lostChanging(string value);
    partial void Ongps_lostChanged();
    partial void Onimage_cam1Changing(string value);
    partial void Onimage_cam1Changed();
    partial void Onimage_cam2Changing(string value);
    partial void Onimage_cam2Changed();
    partial void OnrfidChanging(string value);
    partial void OnrfidChanged();
    partial void OnobdChanging(string value);
    partial void OnobdChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    #endregion
		
		public online_record()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivedTime", DbType="NChar(25)")]
		public string receivedTime
		{
			get
			{
				return this._receivedTime;
			}
			set
			{
				if ((this._receivedTime != value))
				{
					this.OnreceivedTimeChanging(value);
					this.SendPropertyChanging();
					this._receivedTime = value;
					this.SendPropertyChanged("receivedTime");
					this.OnreceivedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NChar(10)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NChar(10)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="NChar(10)")]
		public string speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnc", DbType="NChar(10)")]
		public string mnc
		{
			get
			{
				return this._mnc;
			}
			set
			{
				if ((this._mnc != value))
				{
					this.OnmncChanging(value);
					this.SendPropertyChanging();
					this._mnc = value;
					this.SendPropertyChanged("mnc");
					this.OnmncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lac", DbType="NChar(10)")]
		public string lac
		{
			get
			{
				return this._lac;
			}
			set
			{
				if ((this._lac != value))
				{
					this.OnlacChanging(value);
					this.SendPropertyChanging();
					this._lac = value;
					this.SendPropertyChanged("lac");
					this.OnlacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sos", DbType="NChar(10)")]
		public string sos
		{
			get
			{
				return this._sos;
			}
			set
			{
				if ((this._sos != value))
				{
					this.OnsosChanging(value);
					this.SendPropertyChanging();
					this._sos = value;
					this.SendPropertyChanged("sos");
					this.OnsosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strong_box_open", DbType="NChar(10)")]
		public string strong_box_open
		{
			get
			{
				return this._strong_box_open;
			}
			set
			{
				if ((this._strong_box_open != value))
				{
					this.Onstrong_box_openChanging(value);
					this.SendPropertyChanging();
					this._strong_box_open = value;
					this.SendPropertyChanged("strong_box_open");
					this.Onstrong_box_openChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine_on", DbType="NChar(10)")]
		public string engine_on
		{
			get
			{
				return this._engine_on;
			}
			set
			{
				if ((this._engine_on != value))
				{
					this.Onengine_onChanging(value);
					this.SendPropertyChanging();
					this._engine_on = value;
					this.SendPropertyChanged("engine_on");
					this.Onengine_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stopping", DbType="NChar(10)")]
		public string stopping
		{
			get
			{
				return this._stopping;
			}
			set
			{
				if ((this._stopping != value))
				{
					this.OnstoppingChanging(value);
					this.SendPropertyChanging();
					this._stopping = value;
					this.SendPropertyChanged("stopping");
					this.OnstoppingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps_lost", DbType="NChar(10)")]
		public string gps_lost
		{
			get
			{
				return this._gps_lost;
			}
			set
			{
				if ((this._gps_lost != value))
				{
					this.Ongps_lostChanging(value);
					this.SendPropertyChanging();
					this._gps_lost = value;
					this.SendPropertyChanged("gps_lost");
					this.Ongps_lostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_cam1", DbType="NChar(10)")]
		public string image_cam1
		{
			get
			{
				return this._image_cam1;
			}
			set
			{
				if ((this._image_cam1 != value))
				{
					this.Onimage_cam1Changing(value);
					this.SendPropertyChanging();
					this._image_cam1 = value;
					this.SendPropertyChanged("image_cam1");
					this.Onimage_cam1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_cam2", DbType="NChar(10)")]
		public string image_cam2
		{
			get
			{
				return this._image_cam2;
			}
			set
			{
				if ((this._image_cam2 != value))
				{
					this.Onimage_cam2Changing(value);
					this.SendPropertyChanging();
					this._image_cam2 = value;
					this.SendPropertyChanged("image_cam2");
					this.Onimage_cam2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfid", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string rfid
		{
			get
			{
				return this._rfid;
			}
			set
			{
				if ((this._rfid != value))
				{
					this.OnrfidChanging(value);
					this.SendPropertyChanging();
					this._rfid = value;
					this.SendPropertyChanged("rfid");
					this.OnrfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obd", DbType="NChar(10)")]
		public string obd
		{
			get
			{
				return this._obd;
			}
			set
			{
				if ((this._obd != value))
				{
					this.OnobdChanging(value);
					this.SendPropertyChanging();
					this._obd = value;
					this.SendPropertyChanged("obd");
					this.OnobdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="NChar(20)")]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.history_record")]
	public partial class history_record : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _imei;
		
		private string _receivedTime;
		
		private string _longitude;
		
		private string _latitude;
		
		private string _speed;
		
		private string _mnc;
		
		private string _lac;
		
		private string _sos;
		
		private string _strong_box_open;
		
		private string _engine_on;
		
		private string _stopping;
		
		private string _gps_lost;
		
		private string _image_cam1;
		
		private string _image_cam2;
		
		private string _rfid;
		
		private string _obd;
		
		private string _version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OnreceivedTimeChanging(string value);
    partial void OnreceivedTimeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(string value);
    partial void OnlatitudeChanged();
    partial void OnspeedChanging(string value);
    partial void OnspeedChanged();
    partial void OnmncChanging(string value);
    partial void OnmncChanged();
    partial void OnlacChanging(string value);
    partial void OnlacChanged();
    partial void OnsosChanging(string value);
    partial void OnsosChanged();
    partial void Onstrong_box_openChanging(string value);
    partial void Onstrong_box_openChanged();
    partial void Onengine_onChanging(string value);
    partial void Onengine_onChanged();
    partial void OnstoppingChanging(string value);
    partial void OnstoppingChanged();
    partial void Ongps_lostChanging(string value);
    partial void Ongps_lostChanged();
    partial void Onimage_cam1Changing(string value);
    partial void Onimage_cam1Changed();
    partial void Onimage_cam2Changing(string value);
    partial void Onimage_cam2Changed();
    partial void OnrfidChanging(string value);
    partial void OnrfidChanged();
    partial void OnobdChanging(string value);
    partial void OnobdChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    #endregion
		
		public history_record()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivedTime", DbType="NChar(25)")]
		public string receivedTime
		{
			get
			{
				return this._receivedTime;
			}
			set
			{
				if ((this._receivedTime != value))
				{
					this.OnreceivedTimeChanging(value);
					this.SendPropertyChanging();
					this._receivedTime = value;
					this.SendPropertyChanged("receivedTime");
					this.OnreceivedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NChar(10)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NChar(10)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="NChar(10)")]
		public string speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnc", DbType="NChar(10)")]
		public string mnc
		{
			get
			{
				return this._mnc;
			}
			set
			{
				if ((this._mnc != value))
				{
					this.OnmncChanging(value);
					this.SendPropertyChanging();
					this._mnc = value;
					this.SendPropertyChanged("mnc");
					this.OnmncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lac", DbType="NChar(10)")]
		public string lac
		{
			get
			{
				return this._lac;
			}
			set
			{
				if ((this._lac != value))
				{
					this.OnlacChanging(value);
					this.SendPropertyChanging();
					this._lac = value;
					this.SendPropertyChanged("lac");
					this.OnlacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sos", DbType="NChar(10)")]
		public string sos
		{
			get
			{
				return this._sos;
			}
			set
			{
				if ((this._sos != value))
				{
					this.OnsosChanging(value);
					this.SendPropertyChanging();
					this._sos = value;
					this.SendPropertyChanged("sos");
					this.OnsosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strong_box_open", DbType="NChar(10)")]
		public string strong_box_open
		{
			get
			{
				return this._strong_box_open;
			}
			set
			{
				if ((this._strong_box_open != value))
				{
					this.Onstrong_box_openChanging(value);
					this.SendPropertyChanging();
					this._strong_box_open = value;
					this.SendPropertyChanged("strong_box_open");
					this.Onstrong_box_openChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine_on", DbType="NChar(10)")]
		public string engine_on
		{
			get
			{
				return this._engine_on;
			}
			set
			{
				if ((this._engine_on != value))
				{
					this.Onengine_onChanging(value);
					this.SendPropertyChanging();
					this._engine_on = value;
					this.SendPropertyChanged("engine_on");
					this.Onengine_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stopping", DbType="NChar(10)")]
		public string stopping
		{
			get
			{
				return this._stopping;
			}
			set
			{
				if ((this._stopping != value))
				{
					this.OnstoppingChanging(value);
					this.SendPropertyChanging();
					this._stopping = value;
					this.SendPropertyChanged("stopping");
					this.OnstoppingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps_lost", DbType="NChar(10)")]
		public string gps_lost
		{
			get
			{
				return this._gps_lost;
			}
			set
			{
				if ((this._gps_lost != value))
				{
					this.Ongps_lostChanging(value);
					this.SendPropertyChanging();
					this._gps_lost = value;
					this.SendPropertyChanged("gps_lost");
					this.Ongps_lostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_cam1", DbType="NChar(10)")]
		public string image_cam1
		{
			get
			{
				return this._image_cam1;
			}
			set
			{
				if ((this._image_cam1 != value))
				{
					this.Onimage_cam1Changing(value);
					this.SendPropertyChanging();
					this._image_cam1 = value;
					this.SendPropertyChanged("image_cam1");
					this.Onimage_cam1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_cam2", DbType="NChar(10)")]
		public string image_cam2
		{
			get
			{
				return this._image_cam2;
			}
			set
			{
				if ((this._image_cam2 != value))
				{
					this.Onimage_cam2Changing(value);
					this.SendPropertyChanging();
					this._image_cam2 = value;
					this.SendPropertyChanged("image_cam2");
					this.Onimage_cam2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfid", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string rfid
		{
			get
			{
				return this._rfid;
			}
			set
			{
				if ((this._rfid != value))
				{
					this.OnrfidChanging(value);
					this.SendPropertyChanging();
					this._rfid = value;
					this.SendPropertyChanged("rfid");
					this.OnrfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obd", DbType="NChar(10)")]
		public string obd
		{
			get
			{
				return this._obd;
			}
			set
			{
				if ((this._obd != value))
				{
					this.OnobdChanging(value);
					this.SendPropertyChanging();
					this._obd = value;
					this.SendPropertyChanged("obd");
					this.OnobdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="NChar(20)")]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
